
stages:
  - build
  - test

image: python:3.11

before_script:
  - pip install platformio pytest pyserial

build_firmware:
  stage: build
  script:
    - platformio run
  artifacts:
    paths:
      - .pio/build
    expire_in: 1 week

run_tests:
  stage: test
  script:
    - pytest -m "not hil"
  needs:
    - build_firmware




