[env:Scanner]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM7
monitor_port = COM7
board_build.partitions = huge_app.csv
board_build.psram = enabled

build_flags = 
    -DMBEDTLS_SSL_MAX_CONTENT_LEN=4096
    -DMBEDTLS_SSL_IN_CONTENT_LEN=4096
    -DMBEDTLS_SSL_OUT_CONTENT_LEN=4096

lib_deps = 
    bblanchon/ArduinoJson@^6.21.2
    knolleary/PubSubClient
    mikalhart/TinyGPSPlus
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    mcci-catena/MCCI LoRaWAN LMIC library@^5.0.1

build_src_filter =
    +<*>
    -<hil/*>

[env:hil_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM7
monitor_port = COM7

build_flags =
    -DHIL_TEST_MODE

lib_deps =
    bblanchon/ArduinoJson@^6.21.2
     knolleary/PubSubClient
    mikalhart/TinyGPSPlus
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    mcci-catena/MCCI LoRaWAN LMIC library@^5.0.1
    h2zero/NimBLE-Arduino


build_src_filter =
    -<*>
    +<hil/*>
    +<hil/lora_keys.cpp>





    
