; ============================================================
;  PRODUCTION FIRMWARE (Scanner)
;  - Runs your real IoT code
;  - EXCLUDES all HIL files
; ============================================================
[env:Scanner]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM7
monitor_port = COM7
board_build.partitions = huge_app.csv
board_build.psram = enabled

build_flags = 
    -DMBEDTLS_SSL_MAX_CONTENT_LEN=4096
    -DMBEDTLS_SSL_IN_CONTENT_LEN=4096
    -DMBEDTLS_SSL_OUT_CONTENT_LEN=4096

lib_deps = 
    bblanchon/ArduinoJson@^6.21.2
    knolleary/PubSubClient
    mikalhart/TinyGPSPlus
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    mcci-catena/MCCI LoRaWAN LMIC library@^5.0.1

; IMPORTANT: Exclude HIL folder from production firmware
build_src_filter =
    +<*>
    -<hil/*>


; ============================================================
;  HIL FIRMWARE (hil_test)
;  - Runs ONLY the HIL test mode
;  - Includes ONLY hil/* files
;  - Boots directly into startHilTestMode()
; ============================================================
[env:hil_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM7
monitor_port = COM7
;This will select HIL test mode and not run production code. 
; See main.cpp for details.
build_flags =
    -DHIL_TEST_MODE

lib_deps =
    bblanchon/ArduinoJson@^6.21.2
    knolleary/PubSubClient
    mikalhart/TinyGPSPlus
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    mcci-catena/MCCI LoRaWAN LMIC library@^5.0.1
    h2zero/NimBLE-Arduino
<<<<<<< HEAD
=======

>>>>>>> 9a7dc7815eec34bebb1383ab464d8d3cf3a0d96b

; IMPORTANT: Only compile HIL files
build_src_filter =
    -<*>
    +<hil/*>
