      - name: Start Mosquitto MQTT broker
        shell: powershell
        run: |
          Start-Process -FilePath "C:\Program Files\mosquitto\mosquitto.exe" `
            -ArgumentList '-c "C:\Program Files\mosquitto\mosquitto_local.conf" -v'

      - name: Wait for ESP32 reboot
        shell: powershell
        run: |
          Start-Sleep -Seconds 30
